### ISSUE TITLE
Check for SWPs on Intermediate Steps

### ISSUE THREAD

**Issue by LemongrabThree** [andreassommer/ifdiff#3] opened 2023-12-05 13:27 UTC
In the course of solving #1 , we implemented a check for switching points after every step: `analyseSignature`, which is passed as the `OutputFcn` of the solver, computes the RHS one last time. If the signature is different from the signature at the last time step, it flags a switching point.
However, what if an ODE solution only briefly passes a switching point, but then passes back, and all of this happens within one time step? (See example below)
To help decrease the likelihood of this, let us modify IFDIFF to also check for switching points on intermediate steps. This will dramatically increase the number of signature computations and SWP checks, so we should also include a configuration option to turn this off and revert to the current mode of only checking for SWPs at accepted time steps.

Example:
```matlab
function dx = evilRhs(t, x, p)
    dx = zeros(2, 1);
    dx(1) = 2*t;
    if x(1) <= 0.04
        dx(2) = 20;
    else
        dx(2) = 0;
    end
end
```
Bad solution with step size too large (observe how the solver jumps over the minimum):
![badsolution](https://github.com/andreassommer/ifdiff/assets/2468889/d2d2295d-63fd-4012-a089-0bf3667a6abe)

Approximately correct solution with very small step size:
![goodsolution](https://github.com/andreassommer/ifdiff/assets/2468889/f2ddb165-0f7f-494a-8f82-6b7a9ec431f5)

IFDIFF misses the switching point:
![ifdiff-tricked](https://github.com/andreassommer/ifdiff/assets/2468889/d9560608-66f4-402a-886c-7cbf5fb2b576)

**Comment by andreassommer** [comment] 2023-12-05 14:32
I cannot reproduce this. Your example does not specify initial values, so I guessed them from the plot as being [4, -4, 0] over the interval [t0,tf] = [0, 4].
With defauIt accuracy, ode45 stops integration with a warning ("Warning: Failure at t=1.800000e+00.  Unable to meet integration tolerances without reducing the step size below the smallest value allowed (3.552714e-15) at time t."), but IFDIFF integrates fine and captures both switching events as expected (switches are marked as "data1" and "data2" in the plot:

![evilsquare](https://github.com/andreassommer/ifdiff/assets/29658923/f231fd5e-bcbb-4a56-9b66-8561888cae34)

I also have no Idea why there are "bumps" in the "green" line around the switches in your plot example. Your "green" species should be a piecewise linear function (as depicted in the attached plot "Evilsquare Example").
 
Nevertheless, this kind of "evilness" is hardly tractable. One can always "hide" double-switches from detection. In extremum, one could formulate the `if`-condition as `x(1)-epsilon` with epsilon being 1e-50. Basically, this boils down to a point-change of the differential equation, which is meaningless in a Lebesque sense. Furthermore, for small epsilon, the (mathematically exact) solution becomes extremely sensitive to disturbances and as such this is an ill-posed problem. 
For moderate values of epsilon, IFDIFF performs fine as you can see.

Please also note that the "else" part in your code example is superfluous (the assigned variable dx therein is never used, probably dx3 is meant).

**Closed as completed by andreassommer** 2023-12-05 14:32 UTC

**Comment by LemongrabThree** [comment] 2023-12-05 14:45
I used this code to produce the last plot:

```matlab
initvals = [4, -4, 0];

options = odeset("MaxStep", 1, 'AbsTol', 1e-4, 'RelTol', 1e-6);

initPaths();
integrator = @ode45;
datahandle = prepareDatahandleForIntegration( ...
    'evilRhs', ...
    'solver', ...
    func2str(integrator), ...
    'options', ...
    options ...
);
solX = solveODE(datahandle, tspan, initvals, 0); 
T = T_START:0.1:T_END;
X = deval(solX,T);
plot(T, X(1, :), ".b-");
hold on
plot(T, X(3, :), "g-");
hold off
title("IFDIFF");

```

The `'MaxStep', 1` seems to make the difference.

In any case, though, we still need this issue, don't we? This is what we talked about last Friday.
